### ISSUE TITLE
PHYSFS_platformGrabMutex causes EXC_BAD_INSTRUCTION in iOS 10 simulator

### ISSUE THREAD

**Issue by SDLBugzilla** [icculus/physfs#32] opened 2022-05-20 15:40 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Copied error dump from XCode (physfs-error.txt, text/plain, 2017-04-19 17:27:15 -0400, 1085 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3579)

**Reported in version:** all
**Reported for operating system, platform:** MacOS X, Macintosh

# Comments on the original bug report:

On 2017-04-19 17:27:15 -0400, Tyler Funk wrote:

> Created attachment 3579
> Copied error dump from XCode
> 
> This issue is occurring when attempting to run LÃVE 2D on the iOS simulator. I posted in their forums, and they were convinced it was a PhysicsFS issue, not a LÃVE issue.
> 
> I am using the physfs.framework provided in the love-osx-frameworks-0.10.zip download located here: https://love2d.org/sdk/
> 
> If you have questions or need more information, please let me know. The crash does not provide much of a stack trace but I'll do what I can.
> 
> LÃVE version: 0.10.1
> XCode version: 8.3.2 (8E2002)
> iOS Simulator version: 10.0
> iOS Simulation: iPhone 6s - iOS 10.3 (14E269)

**Comment by slime73** [comment] 2022-05-20 23:59
You can probably close this one - I think LÖVE 0.10 used physfs 2.0, and a lot has changed in both LÖVE and physfs since then. I haven't reproduced this locally recently, at least.

**Closed** 2022-05-21 03:07 UTC
